using CMS.Base;

namespace Kentico.Xperience.Google.SearchConsole.Constants
{
    /// <summary>
    /// Constants used by the Google Search Console integration.
    /// </summary>
    public static class SearchConsoleConstants
    {
        /// <summary>
        /// The report UniGrid mass action to refresh indexed statuses.
        /// </summary>
        public const string ACTION_REFRESH_DATA = "refreshdata";


        /// <summary>
        /// The report UniGrid mass action to request indexing.
        /// </summary>
        public const string ACTION_REQUEST_INDEXING = "requestindexing";


        /// <summary>
        /// The name of the user utilizing the Google APIs.
        /// </summary>
        public const string DEFAULT_USER = "searchconsoleuser";


        /// <summary>
        /// The application setting storing the application name.
        /// </summary>
        public const string APPSETTING_APPLICATIONNAME = "CMSApplicationName";


        /// <summary>
        /// The path of the page to navigate to after Google authentication, to obtain the token.
        /// </summary>
        public const string OAUTH_CALLBACK = "CMSModules/Kentico.Xperience.Google.SearchConsole/Pages/OAuthCallback.aspx";


        /// <summary>
        /// The path of the page to navigate to after obtaining an authentication token (or upon failure).
        /// </summary>
        public const string TOKEN_CALLBACK = "CMSModules/Kentico.Xperience.Google.SearchConsole/Pages/OAuthAuthorizationFinished.aspx";


        /// <summary>
        /// The virtual URL of the mass action dialog.
        /// </summary>
        public const string URL_MASSACTION = "~/CMSModules/Kentico.Xperience.Google.SearchConsole/Pages/SearchConsoleReportMassAction.aspx";


        /// <summary>
        /// The name of the Google JSON credentials file.
        /// </summary>
        public const string CREDENTIALS_FILENAME = "client_secret.json";


        /// <summary>
        /// The absolute filesystem path of the directory used to store data generated by the Google Authorization Flow.
        /// </summary>
        public static readonly string FileStorePhysicalPath = $"{SystemContext.WebApplicationPhysicalPath}\\App_Data\\CMSModules\\Kentico.Xperience.Google.SearchConsole";
    }
}